#!/usr/bin/env node
//
// Pull a release's notes out of CHANGELOG.md.
//
// The release workflow uses this so a GitHub release carries the same text that
// was written for the changelog, rather than an autogenerated commit list. Every
// entry in that file is a "### <version>" heading followed by prose, which is
// exactly the shape a release body wants.
//
//   node scripts/release-notes.js --version 3.12.6           -> the body
//   node scripts/release-notes.js --version 3.12.6 --title   -> "3.12.6 — <summary>"
//
// Exits 0 with a usable fallback when the version has no changelog entry: a
// missing entry should not be able to fail a release.
//
'use strict';

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const wantTitle = args.includes('--title');
const vIndex = args.indexOf('--version');
const version = vIndex >= 0 ? args[vIndex + 1] : '';

if (!version) {
    console.error('usage: release-notes.js --version <x.y.z> [--title]');
    process.exit(2);
}

const changelog = path.join(__dirname, '..', 'CHANGELOG.md');
let lines = [];
try {
    lines = fs.readFileSync(changelog, 'utf8').split(/\r?\n/);
} catch {
    // No changelog at all: fall through to the defaults below.
}

// Collect from the "### <version>" heading up to the next heading of the same
// or higher level. Tolerates a "v" prefix and trailing text on the heading.
const heading = new RegExp(`^#{2,3}\\s+v?${version.replace(/\./g, '\\.')}\\b`);
const body = [];
let inside = false;
for (const line of lines) {
    if (heading.test(line)) {
        inside = true;
        continue;
    }
    if (inside && /^#{1,3}\s/.test(line)) break;
    if (inside) body.push(line);
}

const text = body.join('\n').trim();

if (wantTitle) {
    // The first sentence of the entry, used as the descriptor after the version
    // -- matching the existing release titles, e.g. "3.12.3 — standard language
    // configuration". Strip markdown emphasis and the trailing period, and keep
    // it short enough to read in a release list.
    let summary = (text.split('\n').find((l) => l.trim().length > 0) || '').trim();
    summary = summary.replace(/[*_`]/g, '').replace(/\s+/g, ' ').replace(/\.$/, '');
    if (summary.length > 72) summary = summary.slice(0, 69).trimEnd() + '...';
    console.log(summary ? `${version} — ${summary}` : version);
} else {
    console.log(text || `Release ${version}. See CHANGELOG.md for details.`);
}
